const mockTweets = [
  {
    created_at: 'Thu Nov 01 21:06:23 +0000 2018',
    id: 1058102977553203200,
    id_str: '1058102977553203200',
    text:
      'We visited the offices of Yelp this past week, took a tour of the space, and heard from a panel of engineers (inclu… https://t.co/Ud6eh0DXZz',
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/Ud6eh0DXZz',
          expanded_url: 'https://twitter.com/i/web/status/1058102977553203200',
          display_url: 'twitter.com/i/web/status/1…',
          indices: [117, 140],
        },
      ],
    },
    source: '<a href="http://www.hubspot.com/" rel="nofollow">HubSpot</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 506458865,
      id_str: '506458865',
      name: 'Make School',
      screen_name: 'MakeSchool',
      location: 'San Francisco, CA',
      description:
        'Make School offers a Bachelor’s in Applied Computer Science to prepare students of all backgrounds for jobs at companies like Facebook, Google, Apple.',
      url: 'https://t.co/rfNT6gA2fX',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/rfNT6gA2fX',
              expanded_url: 'http://make.sc/join-us',
              display_url: 'make.sc/join-us',
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 4921,
      friends_count: 4584,
      listed_count: 182,
      created_at: 'Mon Feb 27 21:54:26 +0000 2012',
      favourites_count: 2935,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 2597,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'FFFFFF',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/1047598126876356608/I7Lhsfme_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1047598126876356608/I7Lhsfme_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/506458865/1538432506',
      profile_link_color: '0084B4',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 4,
    favorite_count: 4,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en',
  },
  {
    created_at: 'Thu Nov 01 01:00:10 +0000 2018',
    id: 1057799424628396000,
    id_str: '1057799424628396032',
    text:
      'We had a ton of fun this #halloween 😀👻🎃 Hope you did too! #spooky #trickortreat https://t.co/bZaX8w1VAM',
    truncated: false,
    entities: {
      hashtags: [
        { text: 'halloween', indices: [25, 35] },
        { text: 'spooky', indices: [58, 65] },
        { text: 'trickortreat', indices: [66, 79] },
      ],
      symbols: [],
      user_mentions: [],
      urls: [],
      media: [
        {
          id: 1057799384245649400,
          id_str: '1057799384245649408',
          indices: [80, 103],
          media_url: 'http://pbs.twimg.com/media/Dq4O732WwAA4x_m.jpg',
          media_url_https: 'https://pbs.twimg.com/media/Dq4O732WwAA4x_m.jpg',
          url: 'https://t.co/bZaX8w1VAM',
          display_url: 'pic.twitter.com/bZaX8w1VAM',
          expanded_url:
            'https://twitter.com/MakeSchool/status/1057799424628396032/photo/1',
          type: 'photo',
          sizes: {
            medium: { w: 1200, h: 800, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 680, h: 453, resize: 'fit' },
            large: { w: 2048, h: 1365, resize: 'fit' },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1057799384245649400,
          id_str: '1057799384245649408',
          indices: [80, 103],
          media_url: 'http://pbs.twimg.com/media/Dq4O732WwAA4x_m.jpg',
          media_url_https: 'https://pbs.twimg.com/media/Dq4O732WwAA4x_m.jpg',
          url: 'https://t.co/bZaX8w1VAM',
          display_url: 'pic.twitter.com/bZaX8w1VAM',
          expanded_url:
            'https://twitter.com/MakeSchool/status/1057799424628396032/photo/1',
          type: 'photo',
          sizes: {
            medium: { w: 1200, h: 800, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 680, h: 453, resize: 'fit' },
            large: { w: 2048, h: 1365, resize: 'fit' },
          },
        },
        {
          id: 1057799389001986000,
          id_str: '1057799389001986048',
          indices: [80, 103],
          media_url: 'http://pbs.twimg.com/media/Dq4O8JkWsAAR0A6.jpg',
          media_url_https: 'https://pbs.twimg.com/media/Dq4O8JkWsAAR0A6.jpg',
          url: 'https://t.co/bZaX8w1VAM',
          display_url: 'pic.twitter.com/bZaX8w1VAM',
          expanded_url:
            'https://twitter.com/MakeSchool/status/1057799424628396032/photo/1',
          type: 'photo',
          sizes: {
            small: { w: 680, h: 453, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            large: { w: 2048, h: 1365, resize: 'fit' },
            medium: { w: 1200, h: 800, resize: 'fit' },
          },
        },
        {
          id: 1057799406584582100,
          id_str: '1057799406584582144',
          indices: [80, 103],
          media_url: 'http://pbs.twimg.com/media/Dq4O9LEX0AAM_BV.jpg',
          media_url_https: 'https://pbs.twimg.com/media/Dq4O9LEX0AAM_BV.jpg',
          url: 'https://t.co/bZaX8w1VAM',
          display_url: 'pic.twitter.com/bZaX8w1VAM',
          expanded_url:
            'https://twitter.com/MakeSchool/status/1057799424628396032/photo/1',
          type: 'photo',
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            large: { w: 2048, h: 1365, resize: 'fit' },
            medium: { w: 1200, h: 800, resize: 'fit' },
            small: { w: 680, h: 453, resize: 'fit' },
          },
        },
        {
          id: 1057799414495014900,
          id_str: '1057799414495014913',
          indices: [80, 103],
          media_url: 'http://pbs.twimg.com/media/Dq4O9oiXcAEozTh.jpg',
          media_url_https: 'https://pbs.twimg.com/media/Dq4O9oiXcAEozTh.jpg',
          url: 'https://t.co/bZaX8w1VAM',
          display_url: 'pic.twitter.com/bZaX8w1VAM',
          expanded_url:
            'https://twitter.com/MakeSchool/status/1057799424628396032/photo/1',
          type: 'photo',
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            medium: { w: 1200, h: 800, resize: 'fit' },
            large: { w: 2048, h: 1365, resize: 'fit' },
            small: { w: 680, h: 453, resize: 'fit' },
          },
        },
      ],
    },
    source: '<a href="http://www.hubspot.com/" rel="nofollow">HubSpot</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 506458865,
      id_str: '506458865',
      name: 'Make School',
      screen_name: 'MakeSchool',
      location: 'San Francisco, CA',
      description:
        'Make School offers a Bachelor’s in Applied Computer Science to prepare students of all backgrounds for jobs at companies like Facebook, Google, Apple.',
      url: 'https://t.co/rfNT6gA2fX',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/rfNT6gA2fX',
              expanded_url: 'http://make.sc/join-us',
              display_url: 'make.sc/join-us',
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 4921,
      friends_count: 4584,
      listed_count: 182,
      created_at: 'Mon Feb 27 21:54:26 +0000 2012',
      favourites_count: 2935,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 2597,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'FFFFFF',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/1047598126876356608/I7Lhsfme_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1047598126876356608/I7Lhsfme_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/506458865/1538432506',
      profile_link_color: '0084B4',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 3,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en',
  },
];

export { mockTweets };
